### ISSUE TITLE
eclipse编译有问题

### ISSUE THREAD

**Issue by fdf888** [iamxiatian/xsimilarity#6]
eclipse编译有问题，是否可人帮忙答疑解惑呢，求助求助！

**Comment by fdf888** [comment]
eclipse编译start.java,结果报错：
        Exception in thread "AWT-EventQueue-0" java.lang.Error: Unresolved compilation problem: 
at WordSimlarityUI.createPanel(WordSimlarityUI.java:92)
	at Start.<init>(Start.java:51)
	at Start$1.run(Start.java:84)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
